# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

M_step_PKBD <- function(data, weights, mu_vec, rho, n, d, tol = 1e-6, maxiter = 100L) {
    .Call('_circlus_M_step_PKBD', PACKAGE = 'circlus', data, weights, mu_vec, rho, n, d, tol, maxiter)
}

logLik_PKBD <- function(data, mu_vec, rho) {
    .Call('_circlus_logLik_PKBD', PACKAGE = 'circlus', data, mu_vec, rho)
}

#' @title Random Sampling from PKBD Distributions using ACG Envelopes
#' @description \code{rPKBD_ACG} generates a random sample from PKBD distributions.
#' @param n number of random draws.
#' @param rho a numeric giving the concentration parameter.
#' @param mu a numeric vector giving the mean direction parameter.
#' @return  A vector the generated values.
#' @details The function generates samples from PKBD using ACG envelopes
#' @rdname rPKBD_ACG
#' @useDynLib circlus
#' @importFrom Rcpp evalCpp
rPKBD_ACG <- function(n, rho, mu) {
    .Call('_circlus_rPKBD_ACG', PACKAGE = 'circlus', n, rho, mu)
}

#' @title Random Sampling from spherical Cauchy Distributions
#' @description \code{rsCauchy} generates a random sample from a mixture of multivariate Watson distributions.
#' @param n an integer giving the number of samples to draw.
#' @param rho a numeric value giving the rho parameters.
#' @param mu a numeric vector giving the mu direction parameter.
#' @return  A matrix with rows equal to the generated values.
#' @rdname rsCauchy
#' @export
rsCauchy <- function(n, rho, mu) {
    .Call('_circlus_rsCauchy', PACKAGE = 'circlus', n, rho, mu)
}

M_step_sCauchy <- function(data, weights, n, d, tol = 1e-6, maxiter = 100L) {
    .Call('_circlus_M_step_sCauchy', PACKAGE = 'circlus', data, weights, n, d, tol, maxiter)
}

logLik_sCauchy <- function(data, mu_vec, rho) {
    .Call('_circlus_logLik_sCauchy', PACKAGE = 'circlus', data, mu_vec, rho)
}

