# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Random Sampling from PKBD Distributions using ACG Envelopes
#' @description \code{rPKBD_ACG} generates a random sample from PKBD distributions.
#' @param n number of random draws.
#' @param lambda a numeric giving the concentration parameter.
#' @param mu a numeric vector giving the mean direction parameter.
#' @return  A vector the generated values.
#' @details The function generates samples from PKBD using ACG envelopes
#' @rdname rPKBD_ACG
#' @useDynLib PKBD
#' @importFrom Rcpp evalCpp
#' @export
rPKBD_ACG <- function(n, lambda, mu) {
    .Call('_PKBD_rPKBD_ACG', PACKAGE = 'PKBD', n, lambda, mu)
}

